"""Questions table updated for constraints

Revision ID: 304971dfe881
Revises: fce88d35cb9a
Create Date: 2025-04-19 15:11:29.238586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '304971dfe881'
down_revision = 'fce88d35cb9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('parent_question',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('parent_time',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('parent_att',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('followup_att',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('followup_att',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('parent_att',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('parent_time',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('parent_question',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
