"""Initial migration

Revision ID: fce88d35cb9a
Revises: 
Create Date: 2025-04-19 12:35:24.692030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce88d35cb9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('userid', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('profile', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('teachers',
    sa.Column('userid', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('profile', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('userid'),
    sa.UniqueConstraint('email')
    )
    op.create_table('classes',
    sa.Column('classid', sa.String(length=5), nullable=False),
    sa.Column('classname', sa.String(length=100), nullable=False),
    sa.Column('teacher_id', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.userid'], ),
    sa.PrimaryKeyConstraint('classid')
    )
    op.create_table('assignments',
    sa.Column('assignment_id', sa.String(length=5), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('no_ques', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('objective', sa.JSON(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('class_id', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.classid'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('student_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=5), nullable=False),
    sa.Column('class_id', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.classid'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.userid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignment_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.String(length=5), nullable=False),
    sa.Column('student_id', sa.String(length=5), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('solved_questions', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.userid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.String(length=5), nullable=False),
    sa.Column('assignment_id', sa.String(length=5), nullable=False),
    sa.Column('student_id', sa.String(length=5), nullable=False),
    sa.Column('parent_question', sa.Text(), nullable=False),
    sa.Column('followup_question', sa.Text(), nullable=True),
    sa.Column('parent_time', sa.Integer(), nullable=False),
    sa.Column('followup_time', sa.Integer(), nullable=True),
    sa.Column('parent_att', sa.Integer(), nullable=False),
    sa.Column('followup_att', sa.Integer(), nullable=False),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('parent_hints', sa.JSON(), nullable=True),
    sa.Column('followup_hints', sa.JSON(), nullable=True),
    sa.Column('solved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.userid'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('assignment_progress')
    op.drop_table('student_classes')
    op.drop_table('assignments')
    op.drop_table('classes')
    op.drop_table('teachers')
    op.drop_table('students')
    # ### end Alembic commands ###
